// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type AboutDocumentDataSlicesSlice =
  | TitleSlice
  | HighlightSlice
  | ContentSlice
  | GallerySlice

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice> /**
   * Meta Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: about.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: about.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, 'about', Lang>

/**
 * Item in *Collection → Products*
 */
export interface CollectionDocumentDataProductsItem {
  /**
   * Product field in *Collection → Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.products[].product
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  product: prismic.ContentRelationshipField<'detail'>
}

/**
 * Content for Collection documents
 */
interface CollectionDocumentData {
  /**
   * Title field in *Collection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *Collection*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * Products field in *Collection*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: collection.products[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products: prismic.GroupField<Simplify<CollectionDocumentDataProductsItem>>
}

/**
 * Collection document from Prismic
 *
 * - **API ID**: `collection`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<CollectionDocumentData>,
    'collection',
    Lang
  >

/**
 * Item in *Collections → Products*
 */
export interface CollectionsDocumentDataProductsGroupItem {
  /**
   * Collection field in *Collections → Products*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: collections.products_group[].collection
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  collection: prismic.ContentRelationshipField<'collection'>
}

type CollectionsDocumentDataSlicesSlice = PreloaderSlice

/**
 * Content for Collections documents
 */
interface CollectionsDocumentData {
  /**
   * Title field in *Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: collections.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Products field in *Collections*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: collections.products_group[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  products_group: prismic.GroupField<
    Simplify<CollectionsDocumentDataProductsGroupItem>
  >

  /**
   * Slice Zone field in *Collections*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: collections.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<CollectionsDocumentDataSlicesSlice> /**
   * Meta Description field in *Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: collections.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Collections*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: collections.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Collections*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: collections.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Collections document from Prismic
 *
 * - **API ID**: `collections`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CollectionsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CollectionsDocumentData>,
    'collections',
    Lang
  >

/**
 * Item in *Detail → Highlight*
 */
export interface DetailDocumentDataHighlightItem {
  /**
   * Icon field in *Detail → Highlight*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Arrow
   * - **API ID Path**: detail.highlight[].icon
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  icon: prismic.SelectField<'Arrow' | 'Star', 'filled'>

  /**
   * Text field in *Detail → Highlight*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.highlight[].text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  text: prismic.RichTextField
}

/**
 * Item in *Detail → Information*
 */
export interface DetailDocumentDataInformationItem {
  /**
   * Label field in *Detail → Information*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.information[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.RichTextField

  /**
   * Description field in *Detail → Information*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.information[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField
}

type DetailDocumentDataSlicesSlice = never

/**
 * Content for Detail documents
 */
interface DetailDocumentData {
  /**
   * Title field in *Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Collection field in *Detail*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.collection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  collection: prismic.ContentRelationshipField<'collection'>

  /**
   * Product Image field in *Detail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.product_image_01
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image_01: prismic.ImageField<never>

  /**
   * Product Image 2 field in *Detail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.product_image_02
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  product_image_02: prismic.ImageField<never>

  /**
   * Highlight field in *Detail*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.highlight[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  highlight: prismic.GroupField<Simplify<DetailDocumentDataHighlightItem>>

  /**
   * Information field in *Detail*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.information[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  information: prismic.GroupField<Simplify<DetailDocumentDataInformationItem>>

  /**
   * Shop it - Text field in *Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.link_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_text: prismic.KeyTextField

  /**
   * Shop it - Link field in *Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.link_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_url: prismic.KeyTextField

  /**
   * Slice Zone field in *Detail*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<DetailDocumentDataSlicesSlice> /**
   * Meta Description field in *Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: detail.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField

  /**
   * Meta Image field in *Detail*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: detail.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>

  /**
   * Meta Title field in *Detail*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: detail.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField
}

/**
 * Detail document from Prismic
 *
 * - **API ID**: `detail`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DetailDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<DetailDocumentData>, 'detail', Lang>

type HomeDocumentDataSlicesSlice = GallerySlice | PreloaderSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Collection field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.collection
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  collection: prismic.KeyTextField

  /**
   * Button field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.button
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

/**
 * Content for Metadata documents
 */
interface MetadataDocumentData {
  /**
   * Title field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField

  /**
   * Description field in *Metadata*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField

  /**
   * Image field in *Metadata*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: metadata.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Metadata document from Prismic
 *
 * - **API ID**: `metadata`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MetadataDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MetadataDocumentData>,
    'metadata',
    Lang
  >

/**
 * Item in *Navigation → Nav Item*
 */
export interface NavigationDocumentDataNavItemItem {
  /**
   * Link field in *Navigation → Nav Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_item[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField

  /**
   * Label field in *Navigation → Nav Item*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_item[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Name field in *Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField

  /**
   * Nav Item field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.nav_item[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  nav_item: prismic.GroupField<Simplify<NavigationDocumentDataNavItemItem>>
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    'navigation',
    Lang
  >

export type AllDocumentTypes =
  | AboutDocument
  | CollectionDocument
  | CollectionsDocument
  | DetailDocument
  | HomeDocument
  | MetadataDocument
  | NavigationDocument

/**
 * Primary content in *Content → Primary*
 */
export interface ContentSliceDefaultPrimary {
  /**
   * Label field in *Content → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Description field in *Content → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField

  /**
   * Image field in *Content → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: content.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>

  /**
   * Type field in *Content → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Left
   * - **API ID Path**: content.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<'Left' | 'Right', 'filled'>
}

/**
 * Default variation for Content Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<ContentSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Content*
 */
type ContentSliceVariation = ContentSliceDefault

/**
 * Content Shared Slice
 *
 * - **API ID**: `content`
 * - **Description**: Content
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContentSlice = prismic.SharedSlice<'content', ContentSliceVariation>

/**
 * Primary content in *Gallery → Items*
 */
export interface GallerySliceDefaultItem {
  /**
   * Image field in *Gallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
  'default',
  Record<string, never>,
  Simplify<GallerySliceDefaultItem>
>

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<'gallery', GallerySliceVariation>

/**
 * Primary content in *Highlight → Primary*
 */
export interface HighlightSliceDefaultPrimary {
  /**
   * Label field in *Highlight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField

  /**
   * Title field in *Highlight → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField
}

/**
 * Primary content in *Highlight → Items*
 */
export interface HighlightSliceDefaultItem {
  /**
   * Media field in *Highlight → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: highlight.items[].media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  media: prismic.ImageField<never>
}

/**
 * Default variation for Highlight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<HighlightSliceDefaultPrimary>,
  Simplify<HighlightSliceDefaultItem>
>

/**
 * Slice variation for *Highlight*
 */
type HighlightSliceVariation = HighlightSliceDefault

/**
 * Highlight Shared Slice
 *
 * - **API ID**: `highlight`
 * - **Description**: Highlight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightSlice = prismic.SharedSlice<
  'highlight',
  HighlightSliceVariation
>

/**
 * Primary content in *Preloader → Primary*
 */
export interface PreloaderSliceDefaultPrimary {
  /**
   * Text field in *Preloader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: preloader.primary.preloader_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  preloader_text: prismic.RichTextField

  /**
   * Secondary text field in *Preloader → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: preloader.primary.secondary_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  secondary_text: prismic.RichTextField
}

/**
 * Default variation for Preloader Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreloaderSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<PreloaderSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Preloader*
 */
type PreloaderSliceVariation = PreloaderSliceDefault

/**
 * Preloader Shared Slice
 *
 * - **API ID**: `preloader`
 * - **Description**: Preloader
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PreloaderSlice = prismic.SharedSlice<
  'preloader',
  PreloaderSliceVariation
>

/**
 * Primary content in *Title → Primary*
 */
export interface TitleSliceDefaultPrimary {
  /**
   * Title field in *Title → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField
}

/**
 * Default variation for Title Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSliceDefault = prismic.SharedSliceVariation<
  'default',
  Simplify<TitleSliceDefaultPrimary>,
  never
>

/**
 * Slice variation for *Title*
 */
type TitleSliceVariation = TitleSliceDefault

/**
 * Title Shared Slice
 *
 * - **API ID**: `title`
 * - **Description**: Title
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleSlice = prismic.SharedSlice<'title', TitleSliceVariation>

declare module '@prismicio/client' {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataSlicesSlice,
      CollectionDocument,
      CollectionDocumentData,
      CollectionDocumentDataProductsItem,
      CollectionsDocument,
      CollectionsDocumentData,
      CollectionsDocumentDataProductsGroupItem,
      CollectionsDocumentDataSlicesSlice,
      DetailDocument,
      DetailDocumentData,
      DetailDocumentDataHighlightItem,
      DetailDocumentDataInformationItem,
      DetailDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MetadataDocument,
      MetadataDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      NavigationDocumentDataNavItemItem,
      AllDocumentTypes,
      ContentSlice,
      ContentSliceDefaultPrimary,
      ContentSliceVariation,
      ContentSliceDefault,
      GallerySlice,
      GallerySliceDefaultItem,
      GallerySliceVariation,
      GallerySliceDefault,
      HighlightSlice,
      HighlightSliceDefaultPrimary,
      HighlightSliceDefaultItem,
      HighlightSliceVariation,
      HighlightSliceDefault,
      PreloaderSlice,
      PreloaderSliceDefaultPrimary,
      PreloaderSliceVariation,
      PreloaderSliceDefault,
      TitleSlice,
      TitleSliceDefaultPrimary,
      TitleSliceVariation,
      TitleSliceDefault
    }
  }
}
