// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
  content: dynamic(() => import('./Content')),
  gallery: dynamic(() => import('./Gallery')),
  highlight: dynamic(() => import('./Highlight')),
  title: dynamic(() => import('./Title'))
}
